term.clear()
term.setCursorPos(1,1)
print("deleting files...")
fs.delete("startup.lua")
os.sleep(2)
term.clear()
term.setCursorPos(1,1)
print("goodbye...")
os.sleep(1.8)
term.clear()
fs.delete("mineOS")
os.shutdown()
